### ISSUE TITLE
Primitive button error and now doesn't show up.

### ISSUE THREAD

**Issue by spiraloid** [jayanam/fast-carve#17]
not sure how to fix.  tried new scene, it shows up on a new object in a new scene, but my previous scene will now show the button no matter what.  here's the error.

Traceback (most recent call last):
  File "/Users/bay/Library/Application Support/Blender/2.80/scripts/addons/fast-carve-fast-carve-2-8/fc_immediate_mode_op.py", line 138, in modal
    mouse_pos_3d = self.get_3d_for_mouse(mouse_pos_2d, context)
  File "/Users/bay/Library/Application Support/Blender/2.80/scripts/addons/fast-carve-fast-carve-2-8/fc_immediate_mode_op.py", line 85, in get_3d_for_mouse
    mouse_pos_3d = self.shape.get_3d_for_2d(mouse_pos_2d, context)
  File "/Users/bay/Library/Application Support/Blender/2.80/scripts/addons/fast-carve-fast-carve-2-8/types/shape.py", line 101, in get_3d_for_2d
    result =  self._hit.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

location: <unknown location>:-1

**Comment by spiraloid** [comment]
I suspect it has to do with the fact that I renamed my collections

**Comment by jayanam** [comment]
No I dont think so, just fixed a bug that points in that direction, please
try the latest version 0.9.0.2
